// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon512_rounded.png"></link>
        <meta name="theme-color" content="#b8e986" />
      </head>
      <body className="h-svh">
        <div className="h-full bg-gray-500">{children}</div>
      </body>
    </html>
  );
}
